config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :chat_rooms, only: [:new, :create, :show, :index] do
    resources :messages
  end
  
  root 'chat_rooms#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
	belongs_to :sender, foreign_key: :sender_id, class_name: 'User'
	belongs_to :recepient, foreign_key: :recepient_id, class_name: 'User'
  	
  	has_many :messages, dependent: :destroy

  	validates_uniqueness_of :sender_id, scope: :recepient_id

	scope :involving, -> (user) do
		where("chat_rooms.sender_id = ? OR chat_rooms.recepient_id = ?", user.id, user.id)
	end

	scope :between, -> (sender_id, recepient_id) do
		where("(chat_rooms.sender_id = ? AND chat_rooms.recepient_id = ?) OR (chat_rooms.sender_id = ? AND chat_rooms.recepient_id = ?)", sender_id, recepient_id, recepient_id, sender_id)
	end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :chat_room

   validates_presence_of :body, :chat_room_id, :user_id

  def timestamp
    created_at.strftime('%H:%M:%S %d %B %Y')
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :chat_rooms, dependent: :destroy
  has_many :messages, dependent: :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user! 

  before_action :configure_permitted_params, if: :devise_controller?

  protected
  	def configure_permitted_params
  		devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :is_trainer])
  		devise_parameter_sanitizer.permit(:account_update, keys: [:name])
    end
end

app/controllers/chat_rooms_controller.rb
class ChatRoomsController < ApplicationController
  before_action :authenticate_user!

  def index
    @chat_room = ChatRoom.involving(current_user)
    @chat_rooms_all = ChatRoom.all
    @users = User.all
  end

  def show
    @chat_room = ChatRoom.includes(:messages).find_by(id: params[:id])
  end

  def create
    if ChatRoom.between(params[:sender_id], params[:recepient_id]).present?
      @chat_room = ChatRoom.between(params[:sender_id], params[:recepient_id]).first
    else
      @chat_room = ChatRoom.create(chat_room_params)
    end

    redirect_to chat_room_path(@chat_room)
  end

  private

  def chat_room_params
    params.permit(:sender_id, :recepient_id)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
	def create
		@chat_room = ChatRoom.find(params[:chat_room_id])
		@message = @chat_room.messages.create(message_params)
		@message.user_id = current_user.id if current_user
		@message.save
   
   		redirect_to chat_room_path(@chat_room)
    end

    private
    def message_params
    	params.require(:message).permit(:body, :user_id)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, opts = {})
    opts[:alt] = user.name
    image_tag "https://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(user.email)}?s=#{opts.delete(:size) { 40 }}",
              opts
  end
end

app/helpers/chat_rooms_helper.rb
module ChatRoomsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/chat_rooms/index.html.erb
<h1>Online Users</h1>

<% @users.each do |user| %>
  <% if user != current_user %>
    <%= user.name %>
    <%= link_to "Send Message", chat_rooms_path(sender_id: current_user.id, recepient_id: user.id), method: 'post' %>
  <% end %>
  <br>
<% end %>

<h2>My Chats</h2>

<% @chat_rooms_all.each do |chat| %>
  <% if(chat.sender_id = current_user.id || chat.recepient_id = current_user.id) %>
    	<% @users.each do |recepient| %>
  			<% if(recepient.id = chat.recepient_id)%>
    			<%= recepient.name %>
    			<% break %>
  			<% end %>
  		<% end %>
    <%= link_to "Open Chat", chat_rooms_path(sender_id: current_user.id, recepient_id: chat.recepient_id), method: 'post' %>
  <% end %>
  <br>
<% end %>

app/views/chat_rooms/new.html.erb
<h1>Add chat room</h1>

<%= form_for @chat_room do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, autofocus: true, class: 'form-control' %>
  </div>

  <%= f.submit "Add!", class: 'btn btn-primary' %>
<% end %>

app/views/chat_rooms/show.html.erb
<div id="messages">
  <%= render @chat_room.messages %>
</div>

<h6>Send a Message</h6>

<%= render 'messages/form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Proyecto1UX</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render 'partials/navbar' %>
    
    <div class="row">
      <div class="col-md-4 col-md-offset-4">
        <%= render 'partials/messages' %>
      </div>
    </div>

    <div class="container">
      <%= yield %>
    </div>

  </body>
</html>

app/views/messages/_form.html.erb
<%= bootstrap_form_for([@chat_room, @chat_room.messages.build]) do |f| %>
	<div class="row">
		<div class="col-sm-1 col-sm-offset-15">
			<%= f.submit "Send", class: 'btn btn-primary btn-lg' %>
		</div>
		<div class="col-sm-6">
			<%= f.text_area :body, class: 'form-control' %>
		</div>
	</div>

 <% end %>

app/views/messages/_message.html.erb
<div class="card">
  <div class="card-block">
    <div class="row">
      <div class="col-md-1">
        <%= gravatar_for message.user %>
      </div>
      <div class="col-md-5">
        <p class="card-text">
          <span class="text-muted"><%= message.user.name %> 
            <% if(current_user.is_trainer) %>
            <%= "(T)" %>
            <% end %>
            at <%= message.timestamp %> says</span><br>
          <%= message.body %>
        </p>
      </div>
    </div>
  </div>
</div>

app/views/partials/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">X</a>
    <ul>
      <li>
        <%= value %>
      </li>
    </ul>
  </div>
<% end %>

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-inverse  navbar-static-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Chats", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <!--AQUI TAMBIEN-->
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.name %>
              <% if(current_user.is_trainer) %>
              <%= "(T)" %>
              <% end %>

              <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="#"><%= link_to "Edit Profile", edit_user_registration_path %></a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#"><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></a></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <li><%= link_to "Sign In", new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>